enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# config.toml
[Instagram]
#apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
#apkmirror-dpi = "480dpi"

uptodown-dlurl = "https://instagram.en.uptodown.com/android"
#version = "397.1.0.52.81"
#included-patches = "'Limit feed to followed profiles' 'Hide explore feed' 'Hide navigation buttons'"
included-patches = "'Limit feed to followed profiles' 'Hide navigation buttons'"
patcher-args = "-e 'Hide navigation buttons' -OhideReels=true -OhideCreate=true"
arch = "arm64-v8a"
build-mode = "both"


[Reddit]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
build-mode = "both"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"
build-mode = "both"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
version = "9.0.36.683"
